[workspace]
members = ["crates/optionfiles-core", "crates/optionfiles-cli", "crates/optionfiles-gui"]
resolver = "2"

[workspace.package]
version = "0.2.5"
edition = "2024"
rust-version = "1.85"
authors = ["AEFireflyLabs"]
license = "Apache-2.0"

[workspace.dependencies]
optionSDK = { path = "../optionSDK", version = "0.1.3" }

[profile.release]
lto = true
codegen-units = 1
strip = true
